"""失败分析与 M1D 映射的公开契约。"""

from .contracts import (
    EvidenceKind,
    EvidenceRef,
    EvidenceRefV1,
    EvidenceRole,
    FailureAnalysisReport,
    FailureAnalysisReportV1,
    FailureAttribution,
    FailureCategory,
    FailureLayer,
    GateDecision,
    GateRoute,
    InvariantCheck,
    InvariantCheckV1,
    InvariantKind,
    InvariantResult,
    ReconstructabilityGate,
    ReconstructabilityGateV1,
    Recoverability,
    analysis_run_id,
    evidence_ref_id,
    failure_analysis_report_id,
    failure_analysis_run_id,
    reconstructability_gate_id,
    validate_failure_analysis_report,
    validate_invariant_check,
    validate_reconstructability_gate,
)

__all__ = [
    "MODEL_ANALYSIS_RUN_SCHEMA",
    "EpisodeOutcome",
    "EvidenceKind",
    "EvidenceRef",
    "EvidenceRefV1",
    "EvidenceRole",
    "FailureAnalysisModelResult",
    "FailureAnalysisReport",
    "FailureAnalysisReportV1",
    "FailureAttribution",
    "FailureCategory",
    "FailureLayer",
    "GateDecision",
    "GateRoute",
    "InvariantCheck",
    "InvariantCheckV1",
    "InvariantKind",
    "InvariantResult",
    "ModelAnalysisStatus",
    "ReconstructabilityGate",
    "ReconstructabilityGateV1",
    "Recoverability",
    "analysis_run_id",
    "analyze_failure",
    "evidence_ref_id",
    "failure_analysis_report_id",
    "failure_analysis_run_id",
    "reconstructability_gate_id",
    "run_failure_analysis_model",
    "validate_failure_analysis_report",
    "validate_invariant_check",
    "validate_reconstructability_gate",
]

from .model_analyzer import (
    EpisodeOutcome,
    FailureAnalysisModelResult,
    ModelAnalysisStatus,
    analyze_failure,
)
from .model_runner import MODEL_ANALYSIS_RUN_SCHEMA, run_failure_analysis_model
